on:
  pull_request:

name: unit-tests

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: nightly

      - name: Install dependencies
        run: cargo fetch

      - name: Run tests
        run: cargo test --all
